#include "VisualPhysics.h"
#include "../State.h"
#include "../Hardware.h"

namespace VisualPhysics {
    
    // Internal state: Velocity and timers that only the physics engine needs to know about
    float tubeVel[TUBES] = {0};
    uint32_t peakHoldTime[TUBES] = {0};

    void update() {
        uint32_t now = millis();

        for (int t = 0; t < TUBES; t++) {
            // Target is the smoothed audio data generated by the AudioAnalyzer
            float target = tubeBandsSmooth[t];

            // Spring Physics Math
            float force = (target - tubeLevel[t]) * 0.28f; // Spring stiffness
            tubeVel[t] = (tubeVel[t] + force) * 0.94f;     // Damping (friction)
            
            // Apply velocity to the current level and clamp it between 0 and 1
            tubeLevel[t] = constrain(tubeLevel[t] + tubeVel[t], 0.0f, 1.0f);

            // Peak Hold Logic (for the little dots at the top of the EQ)
            if (tubeLevel[t] > tubePeak[t]) {
                tubePeak[t] = tubeLevel[t];
                peakHoldTime[t] = now;
            } else if ((now - peakHoldTime[t]) > 1200) {
                // After 1.2 seconds, let the peak dot slowly fall down
                tubePeak[t] *= 0.985f;
            }
        }
    }
}
